### ISSUE TITLE
[BUG]sun.security.provider.certpath.SunCertPathBuilderException 

### ISSUE THREAD

**Issue by journey-wang** [fluid-cloudnative/fluid#1899]
Following the tuorial https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/userguide/get_started.md

After the alluxioruntime created, some erros exist in the logs :

2022-06-06 05:37:25,831 WARN  FileSystemMasterClientServiceHandler - Exit (Error): Mount: request=alluxioPath: "/spark"
ufsPath: "https://mirrors.bit.edu.cn/apache/spark"
options {
  readOnly: false
  shared: false
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: FREE
  }
}
, Error=java.io.IOException: Ufs path https://mirrors.bit.edu.cn/apache/spark does not exist
2022-06-06 05:37:30,942 ERROR HttpUtils - Failed to execute URL request: https://mirrors.bit.edu.cn/apache/spark
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)

**Comment by cheyang** [comment]
It is a problem of a certain computing node, and it needs to be authenticated when accessing the external network.
