### ISSUE TITLE
[BUG] When I testing the testcase, alluxio master will crashloopbackoff.

### ISSUE THREAD

**Issue by yangyuliufeng** [fluid-cloudnative/fluid#857]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid v0.6 master 
commit id=5d13d93
**Describe the bug**
When I testing the testcase ( hostpath、pvc accelerate ), alluxio master will crashloopbackoff.

``` bash
$ kubectl logs imagenet-master-0   -c alluxio-master
2021-06-07 09:19:56,547 INFO  FileSystemMasterFactory - Creating alluxio.master.file.FileSystemMaster 
2021-06-07 09:19:56,547 INFO  MetaMasterFactory - Creating alluxio.master.meta.MetaMaster 
2021-06-07 09:19:56,547 INFO  TableMasterFactory - Creating alluxio.master.table.TableMaster 
2021-06-07 09:19:56,547 INFO  BlockMasterFactory - Creating alluxio.master.block.BlockMaster 
2021-06-07 09:19:56,547 INFO  MetricsMasterFactory - Creating alluxio.master.metrics.MetricsMaster 
2021-06-07 09:19:56,592 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-release-2.5.0-2-SNAPSHOT/lib
2021-06-07 09:19:56,689 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio-release-2.5.0-2-SNAPSHOT/extensions
2021-06-07 09:19:56,721 INFO  MetricsSystem - Starting sinks with config: {}.
2021-06-07 09:19:56,723 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-8952781624977616248. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2021-06-07 09:19:56,755 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=132.252.41.86, rack=null)
2021-06-07 09:19:56,758 INFO  UnderDatabaseRegistry - Loading udb jars from /opt/alluxio-release-2.5.0-2-SNAPSHOT/lib
2021-06-07 09:19:56,786 INFO  UnderDatabaseRegistry - Registered UDBs: hive,glue
2021-06-07 09:19:56,787 INFO  LayoutRegistry - Registered Table Layouts: hive
2021-06-07 09:19:56,961 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/blocks
2021-06-07 09:19:57,136 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/inodes
2021-06-07 09:19:57,236 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/inodes
2021-06-07 09:19:57,248 INFO  ProcessUtils - Starting Alluxio master @132.252.41.86:20000.
2021-06-07 09:19:57,249 INFO  ProcessUtils - Running under Java 1.8.0_282
2021-06-07 09:19:57,277 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/blocks
2021-06-07 09:19:57,283 INFO  UfsJournalCheckpointThread - BlockMaster: Journal checkpoint thread started.
2021-06-07 09:19:57,283 INFO  UfsJournalCheckpointThread - TableMaster: Journal checkpoint thread started.
2021-06-07 09:19:57,309 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/inodes
2021-06-07 09:19:57,311 INFO  UfsJournalCheckpointThread - MetaMaster: Journal checkpoint thread started.
2021-06-07 09:19:57,311 INFO  UfsJournalCheckpointThread - FileSystemMaster: Journal checkpoint thread started.
2021-06-07 09:19:57,311 INFO  UfsJournalCheckpointThread - MetricsMaster: Journal checkpoint thread started.
2021-06-07 09:19:57,312 INFO  UfsJournalCheckpointThread - BlockMaster: Journal checkpointer shutdown has been initiated.
2021-06-07 09:19:57,312 INFO  UfsJournalCheckpointThread - TableMaster: Journal checkpointer shutdown has been initiated.
2021-06-07 09:19:57,312 INFO  UfsJournalCheckpointThread - FileSystemMaster: Journal checkpointer shutdown has been initiated.
2021-06-07 09:19:57,312 INFO  UfsJournalCheckpointThread - MetaMaster: Journal checkpointer shutdown has been initiated.
2021-06-07 09:19:57,312 INFO  UfsJournalCheckpointThread - MetricsMaster: Journal checkpointer shutdown has been initiated.
2021-06-07 09:19:59,286 INFO  AbstractJournalProgressLogger - UfsJournal(/journal/BlockMaster/v1)|current SN: 0|entries in last 2000ms=0
2021-06-07 09:19:59,312 INFO  AbstractJournalProgressLogger - UfsJournal(/journal/MetaMaster/v1)|current SN: 0|entries in last 2000ms=0
2021-06-07 09:19:59,312 INFO  AbstractJournalProgressLogger - UfsJournal(/journal/FileSystemMaster/v1)|current SN: 0|entries in last 2000ms=0
2021-06-07 09:19:59,312 INFO  AbstractJournalProgressLogger - UfsJournal(/journal/MetricsMaster/v1)|current SN: 0|entries in last 2000ms=0
2021-06-07 09:20:00,285 INFO  AbstractJournalProgressLogger - UfsJournal(/journal/TableMaster/v1)|current SN: 0|entries in last 3000ms=0
2021-06-07 09:20:03,286 INFO  UfsJournalCheckpointThread - TableMaster: Journal checkpoint thread has been shutdown. No new logs have been found during the quiet period.
2021-06-07 09:20:03,286 INFO  UfsJournalCheckpointThread - BlockMaster: Journal checkpoint thread has been shutdown. No new logs have been found during the quiet period.
2021-06-07 09:20:03,287 INFO  UfsJournalCheckpointThread - TableMaster: Journal shutdown complete
2021-06-07 09:20:03,287 INFO  UfsJournalCheckpointThread - BlockMaster: Journal shutdown complete
2021-06-07 09:20:03,300 INFO  UfsJournal - TableMaster: journal switched to primary mode. location: /journal/TableMaster/v1
2021-06-07 09:20:03,300 INFO  UfsJournal - BlockMaster: journal switched to primary mode. location: /journal/BlockMaster/v1
2021-06-07 09:20:03,313 INFO  UfsJournalCheckpointThread - MetaMaster: Journal checkpoint thread has been shutdown. No new logs have been found during the quiet period.
2021-06-07 09:20:03,313 INFO  UfsJournalCheckpointThread - MetricsMaster: Journal checkpoint thread has been shutdown. No new logs have been found during the quiet period.
2021-06-07 09:20:03,313 INFO  UfsJournalCheckpointThread - MetaMaster: Journal shutdown complete
2021-06-07 09:20:03,313 INFO  UfsJournalCheckpointThread - MetricsMaster: Journal shutdown complete
2021-06-07 09:20:03,314 INFO  UfsJournalCheckpointThread - FileSystemMaster: Journal checkpoint thread has been shutdown. No new logs have been found during the quiet period.
2021-06-07 09:20:03,314 INFO  UfsJournalCheckpointThread - FileSystemMaster: Journal shutdown complete
2021-06-07 09:20:03,314 INFO  UfsJournal - MetaMaster: journal switched to primary mode. location: /journal/MetaMaster/v1
2021-06-07 09:20:03,314 INFO  UfsJournal - MetricsMaster: journal switched to primary mode. location: /journal/MetricsMaster/v1
2021-06-07 09:20:03,315 INFO  UfsJournal - FileSystemMaster: journal switched to primary mode. location: /journal/FileSystemMaster/v1
2021-06-07 09:20:03,326 INFO  AbstractMaster - MetricsMaster: Starting primary master.
2021-06-07 09:20:03,329 INFO  MetricsSystem - Reset all metrics in the metrics system in 2ms
2021-06-07 09:20:03,329 INFO  MetricsStore - Cleared the metrics store and metrics system in 2 ms
2021-06-07 09:20:03,333 INFO  AbstractMaster - BlockMaster: Starting primary master.
2021-06-07 09:20:03,334 INFO  AbstractMaster - FileSystemMaster: Starting primary master.
2021-06-07 09:20:03,334 INFO  DefaultFileSystemMaster - Starting fs master as primary
2021-06-07 09:20:03,486 INFO  UfsJournalLogWriter - Created current log file: UfsJournalFile{location=/journal/BlockMaster/v1/logs/0x0-0x7fffffffffffffff, start=0, end=9223372036854775807, isCheckpoint=false}
2021-06-07 09:20:03,499 INFO  UfsJournalLogWriter - Created current log file: UfsJournalFile{location=/journal/FileSystemMaster/v1/logs/0x0-0x7fffffffffffffff, start=0, end=9223372036854775807, isCheckpoint=false}
2021-06-07 09:20:03,688 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.5.0-2-SNAPSHOT/metastore/inodes
2021-06-07 09:20:03,747 INFO  AbstractMaster - MetaMaster: Starting primary master.
2021-06-07 09:20:03,886 INFO  DefaultMetaMaster - Created new cluster ID f2ebd3e3-da29-4573-9079-659633e4e986
2021-06-07 09:20:03,887 INFO  UfsJournalLogWriter - Created current log file: UfsJournalFile{location=/journal/MetaMaster/v1/logs/0x0-0x7fffffffffffffff, start=0, end=9223372036854775807, isCheckpoint=false}
2021-06-07 09:20:03,927 INFO  BackupTracker - Resetting backup tracker.
2021-06-07 09:20:03,929 INFO  BackupLeaderRole - Creating backup-leader role.
2021-06-07 09:20:03,929 INFO  AbstractMaster - TableMaster: Starting primary master.
2021-06-07 09:20:03,930 INFO  AlluxioMasterProcess - All masters started
2021-06-07 09:20:03,931 INFO  AlluxioMasterProcess - Alluxio master web server version 2.5.0-2 starting. webAddress=/0.0.0.0:20001
2021-06-07 09:20:03,947 INFO  log - Logging initialized @8003ms to org.eclipse.jetty.util.log.Slf4jLog
2021-06-07 09:20:04,084 INFO  WebServer - Alluxio Master Web service starting @ /0.0.0.0:20001
2021-06-07 09:20:04,086 INFO  Server - jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 1.8.0_282-8u282-b08-0ubuntu1~16.04-b08
2021-06-07 09:20:04,122 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@273444fe{/metrics/prometheus,null,AVAILABLE}
2021-06-07 09:20:04,123 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@33bc72d1{/metrics/json,null,AVAILABLE}
2021-06-07 09:20:04,125 WARN  SecurityHandler - ServletContext@o.e.j.s.ServletContextHandler@57a78e3{/,null,STARTING} has uncovered http methods for path: /
2021-06-07 09:20:07,670 INFO  NettyUtils - EPOLL_MODE is available
2021-06-07 09:20:07,969 ERROR ClientMasterSync - Failed to get master address during initialization: alluxio.exception.status.UnavailableException: Failed to handshake with master 132.252.41.86:20000 to load cluster default configuration values: UNAVAILABLE: io exception
2021-06-07 09:20:13,216 WARN  EC2MetadataUtils - Unable to retrieve the requested metadata (/latest/meta-data/product-codes). Failed to connect to service endpoint: 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:382)
	at com.amazonaws.util.EC2MetadataUtils.getProductCodes(EC2MetadataUtils.java:183)
	at alluxio.util.EnvironmentUtils.getEC2ProductCode(EnvironmentUtils.java:88)
	at alluxio.master.meta.UpdateCheck.getEC2Info(UpdateCheck.java:160)
	at alluxio.master.meta.UpdateCheck.getUserAgentEnvironmentString(UpdateCheck.java:112)
	at alluxio.master.meta.UpdateCheck.getUserAgentString(UpdateCheck.java:90)
	at alluxio.master.meta.UpdateCheck.getLatestVersion(UpdateCheck.java:58)
	at alluxio.master.meta.UpdateChecker.heartbeat(UpdateChecker.java:46)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 18 more
2021-06-07 09:20:15,400 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@57a78e3{/,null,AVAILABLE}
2021-06-07 09:20:15,409 INFO  AbstractConnector - Started ServerConnector@40cb8df7{HTTP/1.1, (http/1.1)}{0.0.0.0:20001}
2021-06-07 09:20:15,409 INFO  Server - Started @19464ms
2021-06-07 09:20:15,409 INFO  WebServer - Alluxio Master Web service started @ /0.0.0.0:20001
2021-06-07 09:20:15,411 INFO  AlluxioMasterProcess - Alluxio master version 2.5.0-2 started. bindAddress=/0.0.0.0:20000, connectAddress=132.252.41.86:20000, webAddress=/0.0.0.0:20001
2021-06-07 09:20:15,411 INFO  AlluxioMasterProcess - Starting Alluxio master gRPC server on address /0.0.0.0:20000
2021-06-07 09:20:15,461 INFO  MasterProcess - registered service METRICS_MASTER_CLIENT_SERVICE
2021-06-07 09:20:15,504 INFO  MasterProcess - registered service BLOCK_MASTER_CLIENT_SERVICE
2021-06-07 09:20:15,504 INFO  MasterProcess - registered service BLOCK_MASTER_WORKER_SERVICE
2021-06-07 09:20:15,577 INFO  MasterProcess - registered service FILE_SYSTEM_MASTER_CLIENT_SERVICE
2021-06-07 09:20:15,577 INFO  MasterProcess - registered service FILE_SYSTEM_MASTER_JOB_SERVICE
2021-06-07 09:20:15,577 INFO  MasterProcess - registered service FILE_SYSTEM_MASTER_WORKER_SERVICE
2021-06-07 09:20:15,621 INFO  MasterProcess - registered service META_MASTER_CLIENT_SERVICE
2021-06-07 09:20:15,621 INFO  MasterProcess - registered service META_MASTER_BACKUP_MESSAGING_SERVICE
2021-06-07 09:20:15,621 INFO  MasterProcess - registered service META_MASTER_MASTER_SERVICE
2021-06-07 09:20:15,621 INFO  MasterProcess - registered service META_MASTER_CONFIG_SERVICE
2021-06-07 09:20:15,671 INFO  MasterProcess - registered service TABLE_MASTER_CLIENT_SERVICE
2021-06-07 09:20:15,710 INFO  DefaultSafeModeManager - Rpc server started, waiting 5000ms for workers to register
2021-06-07 09:20:15,710 INFO  AlluxioMasterProcess - Started Alluxio master gRPC server on address 132.252.41.86:20000
2021-06-07 09:20:21,727 WARN  EC2MetadataUtils - Unable to retrieve the requested metadata (/latest/user-data/). Failed to connect to service endpoint: 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:371)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:367)
	at com.amazonaws.util.EC2MetadataUtils.getUserData(EC2MetadataUtils.java:363)
	at alluxio.master.meta.UpdateCheck.getEC2Info(UpdateCheck.java:168)
	at alluxio.master.meta.UpdateCheck.getUserAgentEnvironmentString(UpdateCheck.java:112)
	at alluxio.master.meta.UpdateCheck.getUserAgentString(UpdateCheck.java:90)
	at alluxio.master.meta.UpdateCheck.getLatestVersion(UpdateCheck.java:58)
	at alluxio.master.meta.UpdateChecker.heartbeat(UpdateChecker.java:46)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 18 more
2021-06-07 09:20:30,236 WARN  EC2MetadataUtils - Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:371)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:367)
	at com.amazonaws.util.EC2MetadataUtils.getInstanceInfo(EC2MetadataUtils.java:247)
	at alluxio.util.EnvironmentUtils.isEC2WithInstanceIdentity(EnvironmentUtils.java:166)
	at alluxio.util.EnvironmentUtils.isEC2(EnvironmentUtils.java:69)
	at alluxio.master.meta.UpdateCheck.getEC2Info(UpdateCheck.java:180)
	at alluxio.master.meta.UpdateCheck.getUserAgentEnvironmentString(UpdateCheck.java:112)
	at alluxio.master.meta.UpdateCheck.getUserAgentString(UpdateCheck.java:90)
	at alluxio.master.meta.UpdateCheck.getLatestVersion(UpdateCheck.java:58)
	at alluxio.master.meta.UpdateChecker.heartbeat(UpdateChecker.java:46)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 20 more
2021-06-07 09:20:58,038 WARN  MetaMasterConfigClient - GetConfigHash() returned clusterConfigHash: "4f74f299d09339973122822b781e3954"
pathConfigHash: "d41d8cd98f00b204e9800998ecf8427e"
 in 1244 ms (>=1000 ms)
2021-06-07 09:21:44,821 INFO  JvmPauseMonitor - JVM paused 2826ms
No GCs detected 
max memory = 15837M total memory = 3036M free memory = 1762M
2021-06-07 09:21:57,916 WARN  UnderFileSystemWithLogging - ListStatus(path=/underFSStorage/imagenet/Annotations/CLS-LOC/val) returned OK in 64982 ms (>=10000 ms)
2021-06-07 09:22:01,307 WARN  UnderFileSyst

$ kubectl logs imagenet-master-0  -c alluxio-job-master
2021-06-08 12:03:47,611 INFO  MetricsSystem - Starting sinks with config: {}.
2021-06-08 12:03:47,616 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-1642528563209467270. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2021-06-08 12:03:47,656 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=132.252.41.86, rack=null)
2021-06-08 12:03:47,697 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-release-2.5.0-2-SNAPSHOT/lib
2021-06-08 12:03:47,784 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio-release-2.5.0-2-SNAPSHOT/extensions
2021-06-08 12:03:50,767 ERROR AlluxioJobMasterProcess - java.net.UnknownHostException: jfk8snode43: jfk8snode43: Temporary failure in name resolution
java.lang.RuntimeException: java.net.UnknownHostException: jfk8snode43: jfk8snode43: Temporary failure in name resolution
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:514)
        at alluxio.util.network.NetworkAddressUtils.getLocalHostName(NetworkAddressUtils.java:436)
        at alluxio.util.network.NetworkAddressUtils.getConnectHost(NetworkAddressUtils.java:313)
        at alluxio.underfs.JobUfsManager.connectUfs(JobUfsManager.java:55)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:150)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:171)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
        at alluxio.master.journal.ufs.UfsJournal.<init>(UfsJournal.java:150)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:83)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:53)
        at alluxio.master.AbstractMaster.<init>(AbstractMaster.java:73)
        at alluxio.master.job.JobMaster.<init>(JobMaster.java:157)
        at alluxio.master.AlluxioJobMasterProcess.<init>(AlluxioJobMasterProcess.java:92)
        at alluxio.master.AlluxioJobMasterProcess$Factory.create(AlluxioJobMasterProcess.java:269)
        at alluxio.master.AlluxioJobMaster.main(AlluxioJobMaster.java:45)
Caused by: java.net.UnknownHostException: jfk8snode43: jfk8snode43: Temporary failure in name resolution
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:472)
        ... 14 more
Caused by: java.net.UnknownHostException: jfk8snode43: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 15 more
2021-06-08 12:03:50,773 ERROR AlluxioJobMaster - Failed to create job master process
java.lang.RuntimeException: java.net.UnknownHostException: jfk8snode43: jfk8snode43: Temporary failure in name resolution
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:514)
        at alluxio.util.network.NetworkAddressUtils.getLocalHostName(NetworkAddressUtils.java:436)
        at alluxio.util.network.NetworkAddressUtils.getConnectHost(NetworkAddressUtils.java:313)
        at alluxio.underfs.JobUfsManager.connectUfs(JobUfsManager.java:55)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:150)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:171)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
        at alluxio.master.journal.ufs.UfsJournal.<init>(UfsJournal.java:150)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:83)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:53)
        at alluxio.master.AbstractMaster.<init>(AbstractMaster.java:73)
        at alluxio.master.job.JobMaster.<init>(JobMaster.java:157)
        at alluxio.master.AlluxioJobMasterProcess.<init>(AlluxioJobMasterProcess.java:92)
        at alluxio.master.AlluxioJobMasterProcess$Factory.create(AlluxioJobMasterProcess.java:269)
        at alluxio.master.AlluxioJobMaster.main(AlluxioJobMaster.java:45)
Caused by: java.net.UnknownHostException: jfk8snode43: jfk8snode43: Temporary failure in name resolution
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:472)
        ... 14 more
Caused by: java.net.UnknownHostException: jfk8snode43: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 15 more
2021-06-08 12:03:50,917 INFO  NettyUtils - EPOLL_MODE is available
2021-06-08 12:03:51,319 WARN  MetricsHeartbeatContext - Failed to heartbeat to the metrics master before exit


```

**What you expect to happen:**

**How to reproduce it**
hostpath:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: imagenet
spec:
  mounts:
  - mountPoint: local:///data2/temp/ILSVRC
    name: imagenet
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 132.252.41.86
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: imagenet
spec:
  replicas: 4
  data:
    replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /alluxio/ram
        quota: 150Gi
        high: "0.99"
        low: "0.8"
```
pvc:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: imagenet
spec:
  mounts:
  - mountPoint: pvc:///imagenet
    name: imagenet
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: imagenet
spec:
  replicas: 3
  data:
    replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 150Gi
        high: "0.99"
        low: "0.8"
```

**Additional Information**

**Comment by cheyang** [comment]
@yangyuliufeng Could you show the steps of reproducing the probelm.

**Comment by yangyuliufeng** [comment]
After research, the host which alluxio master running on should have relationship between hostname and ip in /etc/hosts.
Otherwise alluxio cannot parse.
